using AppAutomation.Abstractions;

namespace Unlimotion.UiTests.Authoring.Pages;

[UiControl("MainTabs", UiControlType.Tab, "MainTabs")]
[UiControl("AllTasksTabItem", UiControlType.TabItem, "AllTasksTabItem")]
[UiControl("AllTasksTree", UiControlType.Tree, "AllTasksTree")]
[UiControl("LastCreatedTabItem", UiControlType.TabItem, "LastCreatedTabItem")]
[UiControl("LastCreatedTree", UiControlType.Tree, "LastCreatedTree")]
[UiControl("LastUpdatedTabItem", UiControlType.TabItem, "LastUpdatedTabItem")]
[UiControl("LastUpdatedTree", UiControlType.Tree, "LastUpdatedTree")]
[UiControl("UnlockedTabItem", UiControlType.TabItem, "UnlockedTabItem")]
[UiControl("UnlockedTree", UiControlType.Tree, "UnlockedTree")]
[UiControl("CompletedTabItem", UiControlType.TabItem, "CompletedTabItem")]
[UiControl("CompletedTree", UiControlType.Tree, "CompletedTree")]
[UiControl("ArchivedTabItem", UiControlType.TabItem, "ArchivedTabItem")]
[UiControl("ArchivedTree", UiControlType.Tree, "ArchivedTree")]
[UiControl("LastOpenedTabItem", UiControlType.TabItem, "LastOpenedTabItem")]
[UiControl("LastOpenedTree", UiControlType.Tree, "LastOpenedTree")]
[UiControl("RoadmapTabItem", UiControlType.TabItem, "RoadmapTabItem")]
[UiControl("RoadmapRoot", UiControlType.AutomationElement, "RoadmapRoot")]
[UiControl("RoadmapZoomBorder", UiControlType.AutomationElement, "RoadmapZoomBorder")]
[UiControl("SettingsTabItem", UiControlType.TabItem, "SettingsTabItem")]
[UiControl("SettingsRoot", UiControlType.AutomationElement, "SettingsRoot")]
[UiControl("BackupAutoCheckBox", UiControlType.CheckBox, "BackupAutoCheckBox")]
[UiControl("GitRemoteUrlTextBox", UiControlType.TextBox, "GitRemoteUrlTextBox")]
[UiControl("RefreshGitMetadataButton", UiControlType.Button, "RefreshGitMetadataButton")]
[UiControl("TokenAuthSection", UiControlType.AutomationElement, "TokenAuthSection")]
[UiControl("SwitchRemoteToHttpButton", UiControlType.Button, "SwitchRemoteToHttpButton")]
[UiControl("SwitchRemoteToSshButton", UiControlType.Button, "SwitchRemoteToSshButton")]
[UiControl("SshKeysSection", UiControlType.AutomationElement, "SshKeysSection")]
[UiControl("SshKeyStoragePathTextBox", UiControlType.TextBox, "SshKeyStoragePathTextBox")]
[UiControl("BrowseSshKeyStoragePathButton", UiControlType.Button, "BrowseSshKeyStoragePathButton")]
[UiControl("SshKeyStorageEffectivePathTextBlock", UiControlType.Label, "SshKeyStorageEffectivePathTextBlock")]
[UiControl("SelectedSshPublicKeyComboBox", UiControlType.ComboBox, "SelectedSshPublicKeyComboBox")]
[UiControl("BackupStatusText", UiControlType.Label, "BackupStatusText")]
[UiControl("ConnectRepositoryButton", UiControlType.Button, "ConnectRepositoryButton")]
[UiControl("SyncNowButton", UiControlType.Button, "SyncNowButton")]
[UiControl("PullNowButton", UiControlType.Button, "PullNowButton")]
[UiControl("PushNowButton", UiControlType.Button, "PushNowButton")]
[UiControl("DetailsPaneToggleButton", UiControlType.ToggleButton, "DetailsPaneToggleButton")]
[UiControl("CurrentTaskDetailsScrollViewer", UiControlType.AutomationElement, "CurrentTaskDetailsScrollViewer")]
[UiControl("CurrentTaskCard", UiControlType.AutomationElement, "CurrentTaskCard")]
[UiControl("CurrentTaskHeader", UiControlType.AutomationElement, "CurrentTaskHeader")]
[UiControl("CurrentTaskCommandBar", UiControlType.AutomationElement, "CurrentTaskCommandBar")]
[UiControl("CurrentTaskDescriptionSection", UiControlType.AutomationElement, "CurrentTaskDescriptionSection")]
[UiControl("CurrentTaskPlanningSection", UiControlType.AutomationElement, "CurrentTaskPlanningSection")]
[UiControl("CurrentTaskRepeaterSection", UiControlType.AutomationElement, "CurrentTaskRepeaterSection")]
[UiControl("CurrentTaskRelationsSection", UiControlType.AutomationElement, "CurrentTaskRelationsSection")]
[UiControl("GlobalTaskCreateMenuButton", UiControlType.AutomationElement, "GlobalTaskCreateMenuButton")]
[UiControl("CurrentTaskActionsMenuButton", UiControlType.AutomationElement, "CurrentTaskActionsMenuButton")]
[UiControl("CurrentTaskTitleTextBox", UiControlType.TextBox, "CurrentTaskTitleTextBox")]
[UiControl("CurrentTaskIdTextBlock", UiControlType.AutomationElement, "CurrentTaskIdTextBlock")]
[UiControl("CurrentTaskDescriptionTextBox", UiControlType.TextBox, "CurrentTaskDescriptionTextBox")]
[UiControl("CurrentTaskPlannedBeginPicker", UiControlType.AutomationElement, "CurrentTaskPlannedBeginPicker")]
[UiControl("CurrentTaskSetBeginButton", UiControlType.AutomationElement, "CurrentTaskSetBeginButton")]
[UiControl("CurrentTaskPlannedDurationTextBox", UiControlType.TextBox, "CurrentTaskPlannedDurationTextBox")]
[UiControl("CurrentTaskSetDurationButton", UiControlType.AutomationElement, "CurrentTaskSetDurationButton")]
[UiControl("CurrentTaskPlannedEndPicker", UiControlType.AutomationElement, "CurrentTaskPlannedEndPicker")]
[UiControl("CurrentTaskSetEndButton", UiControlType.AutomationElement, "CurrentTaskSetEndButton")]
[UiControl("CurrentTaskRepeaterSelector", UiControlType.ComboBox, "CurrentTaskRepeaterSelector")]
[UiControl("CurrentTaskParentsRelationAddButton", UiControlType.Button, "CurrentTaskParentsRelationAddButton")]
[UiControl("CurrentTaskParentsRelationAddInput", UiControlType.AutomationElement, "CurrentTaskParentsRelationAddInput")]
[UiControl("CurrentTaskParentsRelationAddCancelButton", UiControlType.Button, "CurrentTaskParentsRelationAddCancelButton")]
[UiControl("CurrentTaskBlockingRelationAddButton", UiControlType.Button, "CurrentTaskBlockingRelationAddButton")]
[UiControl("CurrentTaskBlockingRelationAddInput", UiControlType.AutomationElement, "CurrentTaskBlockingRelationAddInput")]
[UiControl("CurrentTaskBlockingRelationAddCancelButton", UiControlType.Button, "CurrentTaskBlockingRelationAddCancelButton")]
[UiControl("CurrentTaskContainingRelationAddButton", UiControlType.Button, "CurrentTaskContainingRelationAddButton")]
[UiControl("CurrentTaskContainingRelationAddInput", UiControlType.AutomationElement, "CurrentTaskContainingRelationAddInput")]
[UiControl("CurrentTaskContainingRelationAddCancelButton", UiControlType.Button, "CurrentTaskContainingRelationAddCancelButton")]
[UiControl("CurrentTaskBlockedRelationAddButton", UiControlType.Button, "CurrentTaskBlockedRelationAddButton")]
[UiControl("CurrentTaskBlockedRelationAddInput", UiControlType.AutomationElement, "CurrentTaskBlockedRelationAddInput")]
[UiControl("CurrentTaskBlockedRelationAddCancelButton", UiControlType.Button, "CurrentTaskBlockedRelationAddCancelButton")]
[UiControl("CurrentItemParentsTree", UiControlType.Tree, "CurrentItemParentsTree")]
[UiControl("CurrentItemBlockedByTree", UiControlType.Tree, "CurrentItemBlockedByTree")]
[UiControl("CurrentItemContainsTree", UiControlType.Tree, "CurrentItemContainsTree")]
[UiControl("CurrentItemBlocksTree", UiControlType.Tree, "CurrentItemBlocksTree")]
public sealed partial class MainWindowPage : UiPage
{
    public MainWindowPage(IUiControlResolver resolver) : base(resolver)
    {
    }
}
