"""Regenerate the offline UTF-16 regex: python <path-to-this-file>."""

from collections import defaultdict
from hashlib import sha256
from pathlib import Path
import re

DATA = Path(__file__).with_name("emoji-test-17.0.txt")
OUTPUT = Path(__file__).resolve().parents[3] / "Unlimotion.ViewModel" / "EmojiUnicodeData.g.cs"
CHECKSUM = "1d8a944f88d7952f7ef7c5167fef3c67995bcae24543949710231b03a201acda"


def utf16_units(text):
    encoded = text.encode("utf-16-le")
    return [int.from_bytes(encoded[i:i + 2], "little") for i in range(0, len(encoded), 2)]


def unit_pattern(units):
    def escaped(unit):
        return rf"\u{unit:04X}"

    if len(units) == 1:
        return escaped(units[0])
    ranges = []
    start = end = units[0]
    for unit in units[1:]:
        if unit == end + 1:
            end = unit
        else:
            ranges.append((start, end))
            start = end = unit
    ranges.append((start, end))
    return "[" + "".join(escaped(start) if start == end else
                         escaped(start) + "-" + escaped(end) for start, end in ranges) + "]"


def render(node):
    by_suffix = defaultdict(list)
    for unit, child in sorted((key, value) for key, value in node.items() if key is not None):
        by_suffix[render(child)].append(unit)
    branches = [unit_pattern(units) + suffix for suffix, units in by_suffix.items()]
    if not branches:
        return ""
    expression = branches[0] if len(branches) == 1 else "(?:" + "|".join(branches) + ")"
    # Greedy continuation precedes the shorter terminal at every shared prefix.
    return "(?:" + expression + ")?" if None in node else expression


def main():
    raw = DATA.read_bytes()
    if sha256(raw).hexdigest() != CHECKSUM:
        raise ValueError("Unicode corpus checksum mismatch")
    entries = []
    trie = {}
    for line in raw.decode("utf-8").splitlines():
        entry = re.match(r"^([0-9A-F ]+)\s*;\s*(fully-qualified|minimally-qualified|unqualified)\s*#", line)
        if entry is None:
            continue
        units = utf16_units("".join(chr(int(code, 16)) for code in entry[1].split()))
        entries.append(units)
        node = trie
        for unit in units:
            node = node.setdefault(unit, {})
        node[None] = {}
    if len(entries) != 5216:
        raise ValueError("Unexpected Unicode corpus size")
    pattern = render(trie)
    matcher = re.compile(pattern)
    for units in entries:
        text = "".join(chr(unit) for unit in units)
        if matcher.match(text).group() != text:
            raise ValueError("Trie failed longest-prefix recognition")
    chunks = [pattern[i:i + 100] for i in range(0, len(pattern), 100)]
    source = [
        "// <auto-generated />",
        "// Unicode Emoji 17.0: fully-qualified, minimally-qualified and unqualified forms (5216).",
        "// Source: https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt",
        f"// SHA-256: {CHECKSUM}",
        "// Copyright Unicode, Inc. Distributed under Unicode License V3.",
        "// License: Unicode-Emoji.LICENSE.txt. Generator: src/Unlimotion.Test/TestData/Unicode/.",
        "// Longer UTF-16 continuations are greedy before each terminal prefix.",
        "",
        "namespace Unlimotion.ViewModel;",
        "",
        "internal static class EmojiUnicodeData",
        "{",
        "    internal const string Pattern =",
    ]
    for index, chunk in enumerate(chunks):
        source.append('        "' + chunk.replace("\\", "\\\\") + '"' +
                      (";" if index == len(chunks) - 1 else " +"))
    source.append("}")
    OUTPUT.write_text("\n".join(source) + "\n", encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.name}: {len(entries)} forms, {len(pattern)} regex characters")


if __name__ == "__main__":
    main()
