name: Unlimotion debPkg

on:
  release:
    types:
      - published

jobs:
  deb-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
      
    - name: Generate DebPkg
      run: sh ./src/Unlimotion.Desktop/ci/deb/generate-deb-pkg.sh ${{  github.ref_name }}

    - name: Rename DebPkg
      run: cd ./src/Unlimotion.Desktop/bin/Release/net*/linux-x64 && mv ./*.deb ./Unlimotion-${{  github.ref_name }}.deb

    - name: Upload DebPkg To Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./src/Unlimotion.Desktop/bin/Release/net*/linux-x64/Unlimotion-${{  github.ref_name }}.deb

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTIONS: true
  GITHUB_REF_NAME: ${{  github.ref_name }}