name: Unlimotion msiPkg

on:
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  advinst-aip-build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        
    - name: Debug Ref Name
      uses: ./.github/actions/common-steps
        
    - name: Set AppName
      run: |
        file_path=$(find . -type f -name "AppNameDefinitionService.cs")
        
        if [ -n "$file_path" ]; then
         sed -i 's/AppName = "ReleaseTag";/AppName = "${{ github.ref_name }}";/g' "$file_path"
        else
         echo "File not found."
         exit 1
        fi
      shell: bash
        
    - name: Publish
      run: dotnet publish src\Unlimotion.Desktop\Unlimotion.Desktop.csproj -c Release -f net7.0 -r win-x64 -o ${{ github.workspace }}\src\Unlimotion.Desktop\bin\Release\net7.0\win-x64\publish -p:PublishSingleFile=true --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -p:DebugSymbols=false -p:Version=${{  github.ref_name }}

    - name: Build AIP
      uses: caphyon/advinst-github-action@v1.0
      with:
        advinst-version: '20.3.2'
        advinst-enable-automation: 'true'
        aip-path: ${{ github.workspace }}\Unlimotion.aip
        aip-build-name: DefaultBuild
        aip-package-name: Unlimotion-${{  github.ref_name }}.msi
        aip-output-dir:  ${{ github.workspace }}\setup
        aip-commands: |
          SetProperty FOO="foo"
          SetVersion ${{  github.ref_name }}

    - name: Upload MsiPkg to Release
      uses: xresloader/upload-to-github-release@v1.3.11
      with:
        file: ${{ github.workspace }}\setup\Unlimotion-${{  github.ref_name }}.msi
        tags: true